apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-007378ae7d4c91691
  directoryPerms: "700" # Ownership for everything
  basepath: "/expense" # this is for project name in EFS.

